#!/bin/bash
# 
# DaSp test scenario for perfomance testing of dasp_dev script
# Version: 1.02
#
# Style guide: https://google.github.io/styleguide/shell.xml

function init_globals() {
  DEBUG=''
}

function sys_getopts() {
  
  local OPTIND \
        flag

  while getopts 'b' flag
  do
    case "${flag}" in
      b)
        DEBUG='-b'
        readonly DEBUG
      ;;
    esac
  done

}

function main() {

  sys_getopts "$@"

  echo "Perfomance testing..."

  echo -e "\nParam: with tmp file, from some files"
  echo "Items total:" 
  time ../dev/dasp_dev -s mock_perfomance_some/ \
              -f "data*" \
              -d " " \
              -w "[%Y-%b-%d:%H:%M:%S" \
              -k 3 \
              -o 1 \
              ${DEBUG} \
              -t mock_temp_output/test_output \
              "2015-01-01" "2018-12-31" \
              | wc -l

  echo -e "\nParam: with tmp file, from one file"
  echo "Items total:"
  time ../dev/dasp_dev -s mock_perfomance_once/ \
              -f "data*" \
              -d " " \
              -w "[%Y-%b-%d:%H:%M:%S" \
              -k 3 \
              -o 1 \
              ${DEBUG} \
              -t mock_temp_output/test_output \
              "2015-01-01" "2018-12-31" \
              | wc -l

  echo -e "\nParam: without tmp file, from some files"
  echo "Items total:"
  time ../dev/dasp_dev -s mock_perfomance_some/ \
              -f "data*" \
              -d " " \
              -w "[%Y-%b-%d:%H:%M:%S" \
              -k 3 \
              -o 1 \
              ${DEBUG} \
              "2015-01-01" "2018-12-31" \
              | wc -l

  echo -e "\nParam: without tmp file, from one file"
  echo "Items total:"
  time ../dev/dasp_dev -s mock_perfomance_once/ \
              -f "data*" \
              -d " " \
              -w "[%Y-%b-%d:%H:%M:%S" \
              -k 3 \
              -o 1 \
              ${DEBUG} \
              "2015-01-01" "2018-12-31" \
              | wc -l
}

main "$@"