#!/bin/bash
# 
# DaSp test scenario for perfomance testing of dasp script
#
# Style guide: https://google.github.io/styleguide/shell.xml

echo "Perfomance testing..."

echo -e "\nParam: with tmp file, from some files"
echo "Items total:" 
time ../dasp -s mock_perfomance_some/ \
            -f "data*" \
            -d " " \
            -w "[%Y-%b-%d:%H:%M:%S" \
            -k 3 \
            -o 1 \
            -r \
            -t mock_temp_output/test_output \
            "2015-01-01" "2018-12-31" \
            | wc -l

echo -e "\nParam: with tmp file, from one file"
echo "Items total:"
time ../dasp -s mock_perfomance_once/ \
            -f "data*" \
            -d " " \
            -w "[%Y-%b-%d:%H:%M:%S" \
            -k 3 \
            -o 1 \
            -r \
            -t mock_temp_output/test_output \
            "2015-01-01" "2018-12-31" \
            | wc -l

echo -e "\nParam: without tmp file, from some files"
echo "Items total:"
time ../dasp -s mock_perfomance_some/ \
            -f "data*" \
            -d " " \
            -w "[%Y-%b-%d:%H:%M:%S" \
            -k 3 \
            -o 1 \
            -r \
            "2015-01-01" "2018-12-31" \
            | wc -l

echo -e "\nParam: without tmp file, from one file"
echo "Items total:"
time ../dasp -s mock_perfomance_once/ \
            -f "data*" \
            -d " " \
            -w "[%Y-%b-%d:%H:%M:%S" \
            -k 3 \
            -o 1 \
            -r \
            "2015-01-01" "2018-12-31" \
            | wc -l