#!/bin/bash
# 
# LoGen scenario for DaSp LoGen - perfom generating fake logs
# for DaSp qa testing
#
# Style guide: https://google.github.io/styleguide/shell.xml


echo -e "\nGenerating fake logs for dasp testing make long time"
echo -e "\nMkdirs for testing data"

mkdir mock_perfomance_some \
      mock_perfomance_once \
      mock_regular_date \
      mock_timestamp_date \
      mock_custom_months \
      mock_without_years \
      mock_without_century \
      mock_without_seconds \
      mock_temp_output

echo -e "\nForm perfomance data - some files"

./logen -o "mock_perfomance_some/data" \
        -d "+[%Y-%b-%d:%H:%M:%S" \
        -s 4 \
        -g "15,10,\040,3" \
        -b \
        "2016-12-29 12:34:00" "2017-01-07 11:03:00"

echo -e "\nForm perfomance data - one file"

./logen -d "+[%Y-%b-%d:%H:%M:%S" \
        -s 4 \
        -g "15,10,\040,3" \
        -b \
        "2016-12-29 12:34:00" "2017-01-07 11:03:00" \
        > mock_perfomance_once/data

echo -e "\nForm data for regular dates"

./logen -o "mock_regular_date/data" \
        -d "+%H:%M:%S at %Y-%m-%d" \
        -s 198 \
        -g "9,15,;,2" \
        -b \
        "2008-02-01 13:00:00" "2008-03-05 18:12:00"

echo -e "\nForm data for timestamp dates"

./logen -o "mock_timestamp_date/data" \
        -d "+%s" \
        -s 198 \
        -g "9,15,;,2" \
        -b \
        "2008-02-01 13:00:00" "2008-03-05 18:12:00"

echo -e "\nForm data for custom months"

./logen -o "mock_custom_months/data" \
        -d "+%Y-únor-%d:%H:%M:%S" \
        -s 198 \
        -g "9,15,\040,2" \
        -b \
        "2008-02-01 13:00:00" "2008-03-05 18:12:00"

echo -e "\nForm data without years, several fields"

./logen -o "mock_without_years/data" \
        -d "+%b-%d:%H:%M:%S" \
        -s 198 \
        -g "9,15,\040,2" \
        -b \
        "2008-02-01 13:00:00" "2008-03-05 18:12:00"

echo -e "\nForm data without century, several fields"

./logen -o "mock_without_century/data" \
        -d "+%H:%M:%S %y-%b-%d" \
        -s 198 \
        -g "9,15,\040,2" \
        -b \
        "2008-02-01 13:00:00" "2008-03-05 18:12:00"

echo -e "\nForm data without seconds, several fields"

./logen -o "mock_without_seconds/data" \
        -d "+%H:%M %y-%b-%d" \
        -s 198 \
        -g "9,15,\040,2" \
        -b \
        "2008-02-01 13:00:00" "2008-03-05 18:12:00"