#!/bin/bash
# 
# LoGen scenario for DaSp LoGen - perfom clear test dir from fake
# and its folders for DaSp qa testing
#
# Style guide: https://google.github.io/styleguide/shell.xml


echo -e "\nRmdirs with testing data"

rm -r mock_perfomance_some \
      mock_perfomance_once \
      mock_regular_date \
      mock_timestamp_date \
      mock_custom_months \
      mock_without_years \
      mock_without_century \
      mock_without_seconds \
      mock_temp_output